import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#BAF6FF',
  },
  icons1: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  drawerIcon: {
    marginTop: 26,
    marginLeft: 15,
    width: 19,
    height: 19,
  },
  smsIcon: {
    width: 20,
    height: 20,
    marginTop: 25,
    marginLeft: 330,
  },
  listA: {
    borderRadius: 30,
    width: 60,
    height: 60,
    marginLeft: 18,
    marginTop: 7,
    borderColor: '#7797EB',
  },
  listB: {
    borderRadius: 54,
    width: 34,
    height: 34,
    marginLeft: 15,
    marginTop: 11,
    borderColor: '#7797EB',
  },
  likeprofile: {
    borderRadius: 54,
    width: 52,
    height: 51,
    marginLeft: 10,
    marginTop: 35,
    marginRight:10,
    borderColor: '#7797EB',
    borderWidth:2,
  },
  chatsProfile: {
    borderRadius: 54,
    width: 52,
    height: 51,
    marginLeft: 10,
    marginTop: 25,
    marginRight:10,
    borderColor: '#7797EB',
    borderWidth:2,
  },
  moreIcon: {
    width: 20,
    height: 20,
    marginTop: 19,
    marginLeft: 290,
  },
  moreRotateIcon: {
    width: 20,
    height: 20,
    marginTop: 35,
    marginLeft: 32,
    transform: [{ rotate: '90deg' }],
  },
  backIcon: {
    width: 18,
    height: 18,
    marginTop: 22,
    marginLeft: 21.69,
  },
  msgBackIcon: {
    width: 18.62,
    height: 18.62,
    marginTop: 38,
    marginLeft: 20,
  },
  heartIcon: {
    width: 24,
    height: 24,
    marginTop: 21,
    marginLeft: 156,
    marginRight: 6,
    tintColor:'red',
  },
  searchIcon: {
    width: 22,
    height: 22,
    marginTop: 15,
    marginLeft: 15,
    marginRight: 13,
  },
  recImage: {
    width: '100%',
    height: 291,
    marginTop: 9,
    marginLeft: 1,

  },
  C_Icon: {
    width: 20,
    height: 20,
    marginTop: 5,
    marginLeft: 15,
  },
  Emoji_Icon: {
    width: 20,
    height: 20,
    marginTop: 2,
    marginLeft: 3,
  },
  likesText: {
    fontSize: 12,
    width: 45,
    height: 17,
    marginLeft: 15,
    // fontFamily: 'Poppins',
  },
  NameText: {
    fontSize: 16,
    width: 26,
    height: 23,
    marginLeft: 2,
    marginTop: 17,
    fontWeight: 'bold',
    color: '#373737',
    // fontFamily: 'Poppins',
  },
  LText_1: {
    fontSize: 15,
    width: 58,
    height: 20,
    // marginLeft: 2,
    marginTop: 20,
    color: '#373737',
    fontWeight: 'bold',
    // fontFamily: 'Poppins',
  },
  LText_2: {
    fontSize: 13,
    width: 177,
    height: 18,
    color: '#373737',
    fontWeight: 'bold',
    // fontFamily: 'Poppins',
  },
  L_colm: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
  },
  ChatsText_1: {
    fontSize: 16,
    width: 58,
    height: 21,
    marginLeft: 0,
    marginTop: 25,
    color: '#000000',
    fontWeight: 'bold',
    // fontFamily: 'Poppins',
  },
  SecurityText: {
    fontSize: 15,
    width: 348,
    height: 41,
    marginLeft: 12,
    marginTop: 15,
    color: '#000000',
    fontWeight: 'bold',
    lineHeight:21,
    // fontFamily: 'Poppins',
  },
  NameText1: {
    fontSize: 16,
    width: 26,
    height: 23,
    marginLeft: 15,
    marginRight: 5,
    fontWeight: 'bold',
    color: '#373737',
    // fontFamily: 'Poppins',
  },
  NameText2: {
    fontSize: 10,
    width: 54,
    height: 15,
    marginLeft: 15,
    color: '#373737',
    // fontFamily: 'Poppins',
  },
  ProfileText: {
    fontSize: 26,
    width: 87,
    height: 32,
    marginLeft: 18,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
    marginTop:8,
    // fontFamily: 'Segoe UI',
  },
  ProfilePic: {
    borderRadius: 54,
    width: 75,
    height: 75,
    marginLeft: 18,
    marginTop: 12,
    borderColor: '#7797EB',
    borderWidth:2,
  },
  FollowerText: {
    fontSize: 18,
    width: 80,
    height: 48,
    marginLeft: 31,
    marginTop: 12,
    fontWeight: 'bold',
    color: '#000000',
    // fontFamily: 'Segoe UI',
    textAlign: 'center',
  },
  FollowingText: {
    fontSize: 18,
    width: 82,
    height: 48,
    marginLeft: 15,
    marginTop: 12,
    fontWeight: 'bold',
    color: '#000000',
    // fontFamily: 'Segoe UI',
    textAlign: 'center',
  },
  ProfileName: {
    fontSize: 18,
    width: 32,
    height: 24,
    marginLeft: 18,
    marginTop: 23,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
    // fontFamily: 'Segoe UI',
  },
  PostsText: {
    fontSize: 18,
    width: 46,
    height: 48,
    marginLeft: 32,
    marginTop: 12,
    fontWeight: 'bold',
    color: '#000000',
    // fontFamily: 'Segoe UI',
    textAlign: 'center',
  },
  LikesText: {
    fontSize: 22,
    width: 55,
    height: 31,
    marginLeft: 121.69,
    marginTop: 12,
    fontWeight: 'bold',
    color: '#000000',
    // fontFamily: 'Segoe UI',
    textAlign: 'center',
  },
  heartText: {
    fontSize: 22,
    width: 28,
    height: 31,
    marginTop: 18,
    fontWeight: 'bold',
    color: '#3A3A3A',
    // fontFamily: 'Segoe UI',
    textAlign: 'center',
  },
  ProfileDisciption: {
    fontSize: 14,
    width: 216,
    height: 114,
    marginLeft: 18,
    marginTop: 1,
    fontWeight: 'bold',
    color: '#000000',
    padding: 5,
    lineHeight: 19,
    letterSpacing: 0,
    // fontFamily: 'Segoe UI',
  },
  ProfileButton: {
    width: 331,
    height: 36,
    borderRadius: 5,
    alignSelf: 'center',
    backgroundColor: 'white',
    marginBottom: -25,

  },
  FollowingButton: {
    width: 108,
    height: 35,
     backgroundColor: 'transparent',
    borderColor:'#707070',
    borderWidth:1,
    opacity:'100%',
    marginLeft:12,
    marginTop:35,

  },
  FollowingButtonText: {
    alignSelf: 'center',
    marginTop: 7,
    fontSize: 16,
    color: '#000000',
  },
  TimeText: {
    marginLeft:80,
    marginTop:45,
    fontSize: 16,
    fontSize:14,
    color: '#000000',
  },
  ButtonText: {
    alignSelf: 'center',
    marginTop: 7,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000000',
  },
  ProfileIcon1: {
    borderRadius: 54,
    width: 70,
    height: 70,
    marginLeft: 18,
    marginTop: 12,
    borderColor: '#7797EB',
  },
  ProfileIcon2: {
    borderRadius: 54,
    width: 70,
    height: 70,
    marginLeft: 18,
    marginTop: 12,
    borderColor: '#7797EB',
  },
  photo: {
    width: 134,
    marginHorizontal: 1,
    marginVertical: 1,
    height: 126,
  },
  MsgHeader: {
    fontSize: 22,
    width: 35,
    height: 31,
    marginLeft: 148.69,
    marginTop: 30,
    marginBottom:-30,
    fontWeight: 'bold',
    color: '#000000',
    // fontFamily: 'Poppins',
    textAlign: 'center',
  },
  EmailPvtpgHeader: {
    fontSize: 18,
    width: 268,
    height: 25,
    marginLeft: 14.69,
    marginTop: 30,
    fontWeight: 'bold',
    color: '#000000',
    // fontFamily: 'Poppins',
    textAlign: 'center',
  },
  backgroundColor: {
    backgroundColor: '#BAF6FF',
    fontSize: 24,
    width: 382,
    height: 663,
  },
  scene: {
    flex: 1,
  },
  View1: { 
  flexDirection: "row",
  width:364,
  Height:36,
  backgroundColor: 'white',
  borderRadius:10,
  marginTop:7,
  alignSelf:'center',
  },
  search: { 
  color: "#000000", 
  fontWeight: "normal", 
  fontSize: 18, 
  
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default Styles; 